### ISSUE TITLE
tvos support

### ISSUE THREAD

**Issue by tbaranes** [justinweiss/dragongoclient#14]
Do you think to update your pod or carthage to support this new platform soon? Or a branch to avoid breaking the master until CocoaPods release a version working with tvos? 

I don't think you will have any issue to handle it with the current version.

**Comment by justinweiss** [comment]
tvOS looks interesting, but I haven't spent much time looking into it.

I'm not sure what you're asking, though -- what's broken for you?

**Comment by tbaranes** [comment]
Just the podspec needs to be updated, I already try it by forcing the support, boost is working correctly! So, the only need I have is to add tvos support in your podspec by adding the following line:

```
s.tvos.deployment_target = '9.0`
```

Also, don't release your pod right now, cocoapods isn't supporting it in their last release, but they have a workout to work with it.

**Comment by precipice** [comment]
I'm skeptical tvOS is a good platform for dragongoclient. It's certainly possible -- you could use the trackpad to scoot around the board and click to play -- but it doesn't seem ideal to me. Certainly comments would be a pain to enter. There's also no notification system, I believe, so you'd have to get a notification on your phone and then play on your tv, which seems slower than just playing on the phone where the notification arrived.

(I could see tvos as a good platform for observing games, though, especially in a classroom or review setting.)

**Comment by justinweiss** [comment]
Yep, I agree -- iPad and Apple Watch would both be a higher priority.
