### ISSUE TITLE
Build error from last commit

### ISSUE THREAD

**Issue by precipice** [justinweiss/dragongoclient#22]
I think https://github.com/justinweiss/dragongoclient/commit/e207d2622067bf15bc3023889fc244bf57325599 has an error in it. After running bootstrap.sh on a clean checkout, I get one build error on GoBoardView.m: `/Users/marc/Github/dragongoclient/Classes/Views/GoBoardView.m:231:7: Property 'status' not found on object of type 'GoBoardView *'`. It looks like status was removed here: https://github.com/justinweiss/dragongoclient/commit/e207d2622067bf15bc3023889fc244bf57325599#diff-db94c73b40ab3e525592c6afbe24c2afL21

I'll work on a fix.

**Comment by justinweiss** [comment]
Weird, I think that should be ok - as part of rearranging that code, I thought I got rid of it. And I'm pretty sure I'm running that build :-)

I might have forgotten to git add a file -- I'll check it out when I have a chance.

**Comment by precipice** [comment]
No idea, just callin' it as XCode tells me. :) I'll do a clean fork and clone and bootstrap and see if I messed something up. 

Glad to see all the progress! 

-M

**Comment by precipice** [comment]
FWIW I was able to reproduce the error installing everything again from scratch. 😕

**Comment by precipice** [comment]
Man, so great to see it running cleanly. I made a move from the simulator and everything. 👍 

I'll install it on my iPad and play with it.

**Comment by justinweiss** [comment]
Thanks :-) Good to hear. There’s still some autolayout fixes I need to make, but a lot of it works pretty well right now!
